M48
; DRILL file {KiCad 6.0.7} date Thu 08 Jun 2023 16:58:47
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-08T16:58:47+12:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.300
%
G90
G05
T1
X83.1Y-70.9
T2
X95.25Y-81.625
X104.75Y-81.625
T3
X100.0Y-135.05
X100.05Y-65.0
T0
M30
